[package]
name = "rlab-web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
rlab-core = { path = "../rlab-core" }
rlab-db = { path = "../rlab-db" }
rlab-git = { path = "../rlab-git" }